# SPDX-License-Identifier: GPL-2.0
obj-y	+= goodix_gt9xx.o

#goodix_gt9xx-y		+=goodix_tool.o
goodix_gt9xx-y		+=gt9xx.o
goodix_gt9xx-y          +=gt9xx_update.o
#EXTRA_CFLAGS += -Wno-error=date-time
#EXTRA_CFLAGS +=-Wno-date-time